### ISSUE TITLE
Design models and API

### ISSUE THREAD

**Issue by hangpark** [hangpark/jungle.io#1]
# Data Model

**Player**
```
{
    -id: socket id,
    -name: player name,
    +me: whether player is me or others,
    +x: position in x-coordinate,
    +y: position in y-coordinate,
    -type: human or computer,
    +direction: direction angle in radian according to x-coordinate in counter-clockwise,
    +speed: -1, 0, 1, 2,
    +rotate: -1, 0, 1,
    -score: number of victims
}
```

# API

**From client to server**

- `respawn(screenWidth, screenHeight)` - Client wants to (re)spawn in the game. Client sends screen size. Server would emit `welcome`.
- `gotit(name)` - Client has received player info and is ready to start a game. Server would add this player into the player list.
- `playerSendSpeed(speed)` - Client has changed the status by pressing shift or pressing or releasing up or down arrow keys.
- `playerSendRotate(rotate)` - Client has changed the direction by pressing left or right arrow keys.
- `playerSendAttack` - Client performed an attack by pressing space bar.
- `windowResized(screenWidth, screenHeight)` - Client resized the screen.

**From server to client**

- `welcome(player, {gameWidth, gameHeight, backSight, playerSize, attackRadius})`- Server greets client and sends a new `player` object. Client would emit `gotit`.
- `serverTellPlayerMove(visiblePlayers, visibleAttacks, visibleBloods)` - Server calculates players' position according to their direction and status and sends data to a target player.
- `serverTellPlayerDie` - Other adjacent player performed attack and target player is dead.

**Comment by tomtomjhj** [comment]
status를 speed로 바꾸고 거기에 들어가는 값을 
0(stop), 1(walk), 2(sprint), -1(walk backward) 로 한정합시다

**Comment by tomtomjhj** [comment]
https://www.w3schools.com/graphics/tryit.asp?filename=trygame_movement_keyboard

**Comment by tomtomjhj** [comment]
**Attack**
```
{
    attacker: player,
    x: position in x-coordinate,
    y: position in y-coordinate,
    duration: time left for which this attack remains in the field,
}
```

**Comment by tomtomjhj** [comment]
공격을 칼로 써는 것보다는 총으로 쏘는게 뭔가 더 재밌을 거 같은데 어떻게 생각하세요
~~써는 것보다 처리가 쉬울 것 같기도 하고~~
***Bullet***
```
{
    shooter: player,
    x: position in x-coordinate,
    y: position in y-coordinate,
    speed: speed,
    direction: angle,
    duration: ...
}
```

**Comment by tomtomjhj** [comment]
컨셉을 다음과 같이 수정하는게 어떨까요:
1. 2개의 갱단이 대립
2. 갱들이 군중속에 섞여들어가 누가 적인지 일반인(인공지능)인지 구분을 못하는 상태. (팀원은 파란색으로 표시하고 일반인과 적은 모두 검정색으로 표시)
3. 적을 사살하면 점수가 오르고 일반인을 사살하면 점수를 차감

**Comment by tomtomjhj** [comment]
만약 무기를 총으로 바꾼다면 [키보드로 움직이고 마우스로 조준하는 방식](http://diep.io)가 훨씬 좋을 것 같네요
총(마우스 좌클릭) 칼(마우스우클릭)으로 지정하고 총성, 총알(히트스캔 방식이 아니라 탄두가 느린 속도로 날가는 방식)을 추가하면 무기를 상황에 따라 적절히 선택하게끔 유도할 수 있겠네요

**Comment by tomtomjhj** [comment]
만약 마우스 조준을 적용한다면 자신의 뒤를 볼 수 없다는 본래의 의도를 해치게 될텐데 이 부분은 시야의 범위를 부채꼴로 한정하면 해결될 것 같습니다.

**Comment by hangpark** [comment]
attack 모델이 서버 안에서만 쓰이는 게 맞는 것 같아요. 즉 API 차원에서 고려할 필요가 없다, 이 뜻!

**Comment by hangpark** [comment]
칼버전 총버전 두개 만들면 좋을 듯 해요! 칼먼저 만들고 총버전 추가하는 건 별로 어렵진 않을 것 같은데... 일단 하나를 먼저 만드는 게 어떨까요?

**Comment by hangpark** [comment]
그리고 팀전보단 ffa가 더 맞는 것 같아요 컨셉상.

**Comment by tomtomjhj** [comment]
음 그러면 마우스로 조준하는 것으로 변경하는 것은 어떻게 생각하시나요
